### PR TITLE
feat: add iam cnrm resources to sql auth proxy

### PR DESCRIPTION
**Pull request by jmymy**

### CODE REVIEW

**Comment by jmymy** [comment]
How does one get access to the OSS prow to see the logs? I'll have a few more PRs in the coming weeks too and it would be helpful

**Comment by kaariger** [comment]
@jmymy lint tests are failing. Please see below:

```
utils/check_lint.sh
Check license headers
catalog/sql/auth-proxy/iam.yml
Files listed above have incorrect headers. Please run make docker_fix_lint and review changes.
```

**Comment by jmymy** [comment]
> @jmymy lint tests are failing. Please see below:
> 
> 
> 
> ```
> 
> utils/check_lint.sh
> 
> Check license headers
> 
> catalog/sql/auth-proxy/iam.yml
> 
> Files listed above have incorrect headers. Please run make docker_fix_lint and review changes.
> 
> ```

Sigh. I'll fix first thing in the AM. Thanks.

**Comment by jmymy** [comment]
appears to be a bug in the gcr.io/kpt-fn-contrib/generate-kpt-pkg-docs . There is a trailing "

```
1.  Initialize the resource inventory
    ```shell
    kpt live init --namespace ${NAMESPACE}"
    ```
```
https://github.com/GoogleCloudPlatform/blueprints/pull/203/files#diff-1e02dd413183e4453de0e71a646e89ea4c8661140cb71addb9f16140cbba340aR70


looks like it was fixed in this commit.
https://github.com/GoogleContainerTools/kpt-functions-catalog/commit/1adf1d653c2c7de95e12cb5d09aabc3ed4d0b699

**Comment by jmymy** [comment]
fix: https://github.com/GoogleCloudPlatform/blueprints/pull/204

**Review by kaariger — APPROVED** [review]

**Comment by jmymy** [comment]
bump @kaariger @bharathkkb 🙌🏼

**Comment by apeabody** [comment]
Thanks for the contribution @jmymy - Could you rebase your PR?

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @jmymy!

**Pull request merged**
