### PR TITLE
Change syncBranch to master branch

### PR DESCRIPTION
**Pull request by tyorikan**
Changed sync branch to `master` branch since CSR default isn't `main`.

### CODE REVIEW

**Comment by morgante** [comment]
While the CSR UI defaults to `master`, we are trying to promote usage of `main` instead to follow new industry practices. @bharathkkb @kaariger Thoughts?

**Comment by bharathkkb** [comment]
From a CSR perspective, it just means when the page loads there is a warning and asks user to switch branches. I am also planning to switch to main in example foundation (https://github.com/terraform-google-modules/terraform-example-foundation/issues/486) so I think we should continue using `main` here and maybe provide a setter in the future if there is demand.

**Comment by kaariger** [comment]
> While the CSR UI defaults to `master`, we are trying to promote usage of `main` instead to follow new industry practices. @bharathkkb @kaariger Thoughts?

I have internally been using main as well. I do think it's good to adopt the new recommendation and avoid master.

**Comment by morgante** [comment]
@tyorikan Thank you for the PR, but at this time I think we're going to continue preferring `main` as the default. You can of course override it in any instances you check out though.

**Pull request closed without merging**
